version: 3.7
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    build: ./flask-app
    image: flask-image:latest
    container_name: flask-container
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABSE_URI: ${DATABASE_URI}
